---
title: "Schedule"
tbl-colwidths: [4,10,4,4,4,4,6]
---

🔗 ["The Sandbox" coding environment (Github Codespace)](https://classroom.github.com/a/n-LXZmS6)

This schedule is an outline of the topics, with links to all content, and assignments. Note that this may be updated as the module progresses.

+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| Week  | Topics             | Lectures                                                                                                                                           | Notes                                | Code                                                                | Tutorials                                                                         | Problem Sets                          |
+:=====:+====================+:==================================================================================================================================================:+:====================================:+:===================================================================:+:=================================================================================:+:=====================================:+
| 01    | 🐈 Scratch         | [💻(Megan)](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/Megan_wk1.pptx "Megan's intoro slides")                          | [📕](notes/notes_1.html "Notes 1")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src1)  |                                                                                   | [🏠](homework/hw_1.html "Homework 1") |
|       |                    |                                                                                                                                                    |                                      |                                                                     |                                                                                   |                                       |
|       |                    | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_1.pptx)                                                          |                                      |                                                                     |                                                                                   |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 02    | 🟢 C               | [vid ▶](https://youtu.be/Y4SnK7uvF7M "Lecture week 2 C") [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_2.pptx) | [📕](notes/notes_2.html "Notes 2")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src2)  | [👨‍🏫](tutorials/tutorial-week-2.html) \| [🏠](homework/hw_2.html "Homework 2")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 03    | 🟢 Arrays          | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_3.pptx)                                                        | [📕](notes/notes_3.html "Notes 3")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src3)  | [👨‍🏫](tutorials/tutorial-week-3.html) \| [🏠](homework/hw_3.html "Homework 3")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 04    | 🟢 Algorithms      | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_4.pptx)                                                        | [📕](notes/notes_4.html "Notes 4")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src4)  | [👨‍🏫](tutorials/tutorial-week-4.html) \| [🏠](homework/hw_4.html "Homework 4")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 05    | 🟢 Memory          | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_5.pptx)                                                        | [📕](notes/notes_5.html "Notes 5")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src5)  | [👨‍🏫](tutorials/tutorial-week-5.html) \| [🏠](homework/hw_5.html "Homework 5")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 06    | 🟢 Data structures | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_6.pptx)                                                        | [📕](notes/notes_6.html "Notes 6")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src6)  | [👨‍🏫](tutorials/tutorial-week-6.html) \| [🏠](homework/hw_6.html "Homework 6")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 07    | 🐍 Python          | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_7.pptx)                                                        | [📕](notes/notes_7.html "Notes 7")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src7)  | [👨‍🏫](tutorials/tutorial-week-7.html) \| [🏠](homework/hw_7.html "Homework 7")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 08    | 📊 SQL             | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_8.pptx)                                                        | [📕](notes/notes_8.html "Notes 8")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src8)  | [👨‍🏫](tutorials/tutorial-week-8.html) \| [🏠](homework/hw_8.html "Homework 8")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 09    | 🌐 Web programming | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_9.pptx)                                                        | [📕](notes/notes_9.html "Notes 9")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src9)  | [👨‍🏫](tutorials/tutorial-week-9.html) \| [🏠](homework/hw_9.html "Homework 9")     |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 10    | 🐍 Flask           | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_10.pptx)                                                       | [📕](notes/notes_10.html "Notes 10") | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src10) | [👨‍🏫](tutorials/tutorial-week-10.html) \| \[🏠\](homework/hw_10.html "Homework 10" |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+
| 11    | 👋 Wrap up         | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_11.pptx)                                                       | [📕](notes/notes_11.html "Notes 11") |                                                                     |                                                                                   |                                       |
+-------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------+---------------------------------------+

```{r echo = FALSE}
knitr::knit_exit()
```