---
title: "FAQ"
---

## What is the deadline for problem set assessments?

There are several published deadlines for problem set assessments, which can cause confusion.  

The **ultimate** deadline for problem sets is set by the university and can be found in the SQ4007 Assessment (problem set) document linked on the [Harper Adams module page](https://vle.harper-adams.ac.uk/course/view.php?id=282).  This Submission Deadline is **15.00 on 2025-12-11 (Thursday, 11 Dec)**, by which time and date all of your problems sets must be completed and submitted to gain credit for them.

The weekly deadlines on the schedule are the (strongly) suggested pace of work to keep up with the module.  They are not the ultimate deadline for the problem set assessment (i.e. you can submit your problem sets and still gain credit up to 15:00 on 2025-12-11).

------------------------------------------------------------------------

::::: columns
::: {.column width="28%"}
```{=html}
<iframe width="200" height="125" src="https://www.youtube.com/embed/WVPIzkYjxvk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
:::

::: column
## How do I log into The Sandbox coding environment?
:::
:::::

------------------------------------------------------------------------

::::: columns
::: {.column width="28%"}
```{=html}
<iframe width="200" height="125" src="https://www.youtube.com/embed/YnLlfTy-PRw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
:::

::: column
## How do I submit my problem set assignments?
:::
:::::

------------------------------------------------------------------------

## Flipped Classroom: Can I still come to lecture if I don't watch the videos and go through the notes for that week before class?

Yes, of course you can and should! But...

The point of the flipped classroom is to maximise the time spent in class discussing and solving problems. If you don't watch the videos and go through the notes for that week before class, you will miss out on this and potentially fall behind while others are getting on with their problem set work during classtime.

------------------------------------------------------------------------

## Can I just code on my own computer?

The short answer is, heck yeah!! But, you will still need to use our Github Codespaces to submit your work.

However, installing and configuring programming and editing software on your own computer is sometimes complicated and irritating, even for very experienced people. Configuring all the tools we will be using in The Sandbox to be exactly the same on your own computer, operating system, etc., will require advanced skills. Still, you can do it if you want to; most of the tools are open source and free and will work for most tasks. Also, we are here to help support you if you want to try.

If you want to explore this path, here are the main things you need to do:

For a start...

-   Download and install Python (\> v3.11): <https://www.python.org/downloads/>
-   Download and install VS Code (other editors are okay too): <https://code.visualstudio.com/download>
-   Install C/C++ in VS Code: <https://code.visualstudio.com/docs/languages/cpp>
-   Install Git: <https://happygitwithr.com/install-git.html>
-   Install the CS50 library: <https://github.com/cs50/libcs50>

------------------------------------------------------------------------